EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) SELECT o_orderkey FROM ORDERS
WHERE NOT EXISTS(SELECT * FROM LINEITEM WHERE o_orderkey = l_orderkey)
AND NOT EXISTS(SELECT * FROM LINEITEM WHERE l_orderkey IS NULL);
